### PR TITLE
Remove exit statements

### LINKED ISSUE #805: Avoid use of exit-statements
### Description of feature

(Not sure if this should be a feature-issue or bug-issue, anyways here goes...)

Version 3.0.2 of Sarek contains a bunch of `exit`-statement. Here is an example:

https://github.com/nf-core/sarek/blob/bcd7bf9cb98cddec27bb54fb47ee122c09388c02/workflows/sarek.nf#L74

I recently learned from Marcel Ribeiro-Dantas (@mribeirodantas) that those `exit`-statements should probably be replaced by exceptions like, say,

`throw new Exception("Bad stuff happend")`

since "_if Nextflow is running in a subprocess of something else, it [an exit-statement] kills the entire thing_".

What do you say we replace the `exit`-statements with exceptions?

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
Close #805 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

File: lib/WorkflowMain.groovy [hunk 1]
```diff
@@ -2,6 +2,8 @@
 // This file holds several functions specific to the main.nf workflow in the nf-core/sarek pipeline
 //
 
+import nextflow.Nextflow
```
Comment (maxulysse) [inline lib/WorkflowMain.groovy:5]: Do we need to import nextflow.Nextflow if we're not exiting?

**Comment by maxulysse** [comment]
Asking a second review by @robsyme for sanity

File: lib/WorkflowMain.groovy (hunk 1 above)
Comment (robsyme) [reply lib/WorkflowMain.groovy:5]: True. This can be removed.

**Comment by FriederikeHanssen** [comment]
Conda 😡 : 

```
CondaError: No package 'conda-forge/linux-64::libgomp-12.2.0-h65d4601_19' found in cache directories.

```

where does this come from now.

**Comment by maxulysse** [comment]
That's conda, don't wish to much

**Comment by FriederikeHanssen** [comment]
got one conda test to pass by changing nothing, maybe it depends to which runner it is submitted too?

File: workflows/sarek.nf [hunk 2]
```diff
@@ -4,6 +4,7 @@
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
 
+import nextflow.Nextflow
```
Comment (maxulysse) [inline workflows/sarek.nf:7]: I don't think we need that

**Review by maxulysse — APPROVED** [review]
I don't think we need to have that part in a Nextflow script:

```
import nextflow.Nextflow
```

File: workflows/sarek.nf (hunk 2 above)
Comment (FriederikeHanssen) [reply workflows/sarek.nf:7]: it failed with missing nextflow.Nextflow before

Comment (FriederikeHanssen) [reply workflows/sarek.nf:7]: this commit: https://github.com/nf-core/sarek/actions/runs/4565424537/jobs/8062646459

Comment (maxulysse) [reply workflows/sarek.nf:7]: I think this tests is expected to fail

Comment (robsyme) [reply workflows/sarek.nf:7]: The import and qualification with `nextflow.error` prefix are only necessary in Groovy classes pulled into the classpath via inclusion in the `lib` directory. Inside a nextflow files such as `main.nf`, or `workflows/sarek.nf`, the `error` and `exit` methods are always in scope, so we can remove the `import` statement and change all occurrences of `Nextflow.error` to `error`.

File: workflows/sarek.nf [hunk 3]
```diff
@@ -60,9 +61,9 @@ input_sample = params.build_only_index ? Channel.empty() : extract_csv(file(para
 
 // Fails when wrongfull extension for intervals file
 if (params.wes && !params.step == 'annotate') {
-    if (params.intervals && !params.intervals.endsWith("bed")) exit 1, "Target file specified with `--intervals` must be in BED format for targeted data"
+    if (params.intervals && !params.intervals.endsWith("bed"))  Nextflow.error("Target file specified with `--intervals` must be in BED format for targeted data")
```
Comment (robsyme) [inline workflows/sarek.nf:64]:
```suggestion
    if (params.intervals && !params.intervals.endsWith("bed"))  error("Target file specified with `--intervals` must be in BED format for targeted data")
```

File: workflows/sarek.nf [hunk 4]
```diff
@@ -60,9 +61,9 @@ input_sample = params.build_only_index ? Channel.empty() : extract_csv(file(para
...
     else log.warn("Intervals file was provided without parameter `--wes`: Pipeline will assume this is Whole-Genome-Sequencing data.")
-} else if (params.intervals && !params.intervals.endsWith("bed") && !params.intervals.endsWith("list")) exit 1, "Intervals file must end with .bed, .list, or .interval_list"
+} else if (params.intervals && !params.intervals.endsWith("bed") && !params.intervals.endsWith("list")) Nextflow.error("Intervals file must end with .bed, .list, or .interval_list")
```
Comment (robsyme) [inline workflows/sarek.nf:66]:
```suggestion
} else if (params.intervals && !params.intervals.endsWith("bed") && !params.intervals.endsWith("list")) error("Intervals file must end with .bed, .list, or .interval_list")
```

File: workflows/sarek.nf [hunk 5]
```diff
@@ -71,12 +72,10 @@ if (params.step == 'mapping' && params.aligner.contains("dragmap") && !(params.s
 // Fails or warns when missing files or params for ascat
 if (params.tools && params.tools.split(',').contains('ascat')) {
     if (!params.ascat_alleles) {
-        log.error "No allele files were provided for running ASCAT. Please provide a zip folder with allele files."
-        exit 1
+        Nextflow.error("No allele files were provided for running ASCAT. Please provide a zip folder with allele files.")
```
Comment (robsyme) [inline workflows/sarek.nf:75]:
```suggestion
        error("No allele files were provided for running ASCAT. Please provide a zip folder with allele files.")
```

File: workflows/sarek.nf [hunk 6]
```diff
@@ -103,33 +102,29 @@ if (params.tools && params.tools.split(',').contains('mutect2')) {
 // Warns when missing resources for haplotypecaller
 if (!params.dbsnp && !params.known_indels) {
     if (params.step in ['mapping', 'markduplicates', 'prepare_recalibration', 'recalibrate'] && (!params.skip_tools || (params.skip_tools && !params.skip_tools.split(',').contains('baserecalibrator')))) {
-        log.error "Base quality score recalibration requires at least one resource file. Please provide at least one of `--dbsnp` or `--known_indels`\nYou can skip this step in the workflow by adding `--skip_tools baserecalibrator` to the command."
-        exit 1
+        Nextflow.error("Base quality score recalibration requires at least one resource file. Please provide at least one of `--dbsnp` or `--known_indels`\nYou can skip this step in the workflow by adding `--skip_tools baserecalibrator` to the command.")
```
Comment (robsyme) [inline workflows/sarek.nf:105]:
```suggestion
        error("Base quality score recalibration requires at least one resource file. Please provide at least one of `--dbsnp` or `--known_indels`\nYou can skip this step in the workflow by adding `--skip_tools baserecalibrator` to the command.")
```

File: workflows/sarek.nf [hunk 7]
```diff
@@ -103,33 +102,29 @@ if (params.tools && params.tools.split(',').contains('mutect2')) {
...
     }
 }
 if (params.joint_germline && (!params.tools || !params.tools.split(',').contains('haplotypecaller'))) {
-    log.error "The Haplotypecaller should be specified as one of the tools when doing joint germline variant calling. (The Haplotypecaller could be specified by adding `--tools haplotypecaller` to the nextflow command.) "
-    exit 1
+    Nextflow.error("The Haplotypecaller should be specified as one of the tools when doing joint germline variant calling. (The Haplotypecaller could be specified by adding `--tools haplotypecaller` to the nextflow command.) ")
```
Comment (robsyme) [inline workflows/sarek.nf:112]:
```suggestion
    error("The Haplotypecaller should be specified as one of the tools when doing joint germline variant calling. (The Haplotypecaller could be specified by adding `--tools haplotypecaller` to the nextflow command.) ")
```

File: workflows/sarek.nf [hunk 8]
```diff
@@ -103,33 +102,29 @@ if (params.tools && params.tools.split(',').contains('mutect2')) {
...
 }
 if (params.joint_germline && (!params.dbsnp || !params.known_indels || !params.known_snps || params.no_intervals)) {
     log.warn "If Haplotypecaller is specified, without `--dbsnp`, `--known_snps`, `--known_indels` or the associated resource labels (ie `known_snps_vqsr`), no variant recalibration will be done. For recalibration you must provide all of these resources.\nFor more information see VariantRecalibration: https://gatk.broadinstitute.org/hc/en-us/articles/5358906115227-VariantRecalibrator \nJoint germline variant calling also requires intervals in order to genotype the samples. As a result, if `--no_intervals` is set to `true` the joint germline variant calling will not be performed."
 }
 
 // Fails when missing tools for variant_calling or annotate
 if ((params.step == 'variant_calling' || params.step == 'annotate') && !params.tools) {
-    log.error "Please specify at least one tool when using `--step ${params.step}`.\nhttps://nf-co.re/sarek/parameters#tools"
-    exit 1
+    Nextflow.error("Please specify at least one tool when using `--step ${params.step}`.\nhttps://nf-co.re/sarek/parameters#tools")
```
Comment (robsyme) [inline workflows/sarek.nf:120]:
```suggestion
    error("Please specify at least one tool when using `--step ${params.step}`.\nhttps://nf-co.re/sarek/parameters#tools")
```

File: workflows/sarek.nf [hunk 9]
```diff
@@ -103,33 +102,29 @@ if (params.tools && params.tools.split(',').contains('mutect2')) {
...
 }
 
 // Fails when missing sex information for CNV tools
 if (params.tools && (params.tools.split(',').contains('ascat') || params.tools.split(',').contains('controlfreec'))) {
     input_sample.map{
         if (it[0].sex == 'NA' ) {
-            log.error "Please specify sex information for each sample in your samplesheet when using '--tools' with 'ascat' or 'controlfreec'.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-            exit 1
+            Nextflow.error("Please specify sex information for each sample in your samplesheet when using '--tools' with 'ascat' or 'controlfreec'.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:127]:
```suggestion
            error("Please specify sex information for each sample in your samplesheet when using '--tools' with 'ascat' or 'controlfreec'.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 10]
```diff
@@ -1103,8 +1098,7 @@ def extract_csv(csv_file) {
         def line, samplesheet_line_count = 0;
         while ((line = reader.readLine()) != null) {samplesheet_line_count++}
         if (samplesheet_line_count < 2) {
-            log.error "Samplesheet had less than two lines. The sample sheet must be a csv file with a header, so at least two lines."
-            System.exit(1)
+            Nextflow.error("Samplesheet had less than two lines. The sample sheet must be a csv file with a header, so at least two lines.")
```
Comment (robsyme) [inline workflows/sarek.nf:1101]:
```suggestion
           error("Samplesheet had less than two lines. The sample sheet must be a csv file with a header, so at least two lines.")
```

File: workflows/sarek.nf [hunk 11]
```diff
@@ -1118,22 +1112,19 @@ def extract_csv(csv_file) {
         .map{ row ->
             if (params.step == "mapping") {
                 if ( !row.lane ) {  // This also handles the case where the lane is left as an empty string
-                    log.error('The sample sheet should specify a lane for patient "' + row.patient.toString() + '" and sample "' + row.sample.toString() + '".')
-                    System.exit(1)
+                    Nextflow.error('The sample sheet should specify a lane for patient "' + row.patient.toString() + '" and sample "' + row.sample.toString() + '".')
```
Comment (robsyme) [inline workflows/sarek.nf:1115]:
```suggestion
                    error('The sample sheet should specify a lane for patient "' + row.patient.toString() + '" and sample "' + row.sample.toString() + '".')
```

File: workflows/sarek.nf [hunk 12]
```diff
@@ -1118,22 +1112,19 @@ def extract_csv(csv_file) {
...
                 }
                 def patient_sample_lane = [row.patient.toString(), row.sample.toString(), row.lane.toString()]
                 if (patient_sample_lane in patient_sample_lane_combinations) {
-                    log.error('The patient-sample-lane combination "' + row.patient.toString() + '", "' + row.sample.toString() + '", and "' + row.lane.toString() + '" is present multiple times in the sample sheet.')
-                    System.exit(1)
+                    Nextflow.error('The patient-sample-lane combination "' + row.patient.toString() + '", "' + row.sample.toString() + '", and "' + row.lane.toString() + '" is present multiple times in the sample sheet.')
```
Comment (robsyme) [inline workflows/sarek.nf:1119]:
```suggestion
                    error('The patient-sample-lane combination "' + row.patient.toString() + '", "' + row.sample.toString() + '", and "' + row.lane.toString() + '" is present multiple times in the sample sheet.')
```

File: workflows/sarek.nf [hunk 13]
```diff
@@ -1118,22 +1112,19 @@ def extract_csv(csv_file) {
...
                 } else {
                     patient_sample_lane_combinations.add(patient_sample_lane)
                 }
             }
             if (!sample2patient.containsKey(row.sample.toString())) {
                 sample2patient[row.sample.toString()] = row.patient.toString()
             } else if (sample2patient[row.sample.toString()] != row.patient.toString()) {
-                log.error('The sample "' + row.sample.toString() + '" is registered for both patient "' + row.patient.toString() + '" and "' + sample2patient[row.sample.toString()] + '" in the sample sheet.')
-                System.exit(1)
+                Nextflow.error('The sample "' + row.sample.toString() + '" is registered for both patient "' + row.patient.toString() + '" and "' + sample2patient[row.sample.toString()] + '" in the sample sheet.')
```
Comment (robsyme) [inline workflows/sarek.nf:1127]:
```suggestion
               error('The sample "' + row.sample.toString() + '" is registered for both patient "' + row.patient.toString() + '" and "' + sample2patient[row.sample.toString()] + '" in the sample sheet.')
```

File: workflows/sarek.nf [hunk 14]
```diff
@@ -1146,12 +1137,10 @@ def extract_csv(csv_file) {
         .map{ row ->
             sample_count_all++
             if (!(row.patient && row.sample)) {
-                log.error "Missing field in csv file header. The csv file must have fields named 'patient' and 'sample'."
-                System.exit(1)
+                Nextflow.error("Missing field in csv file header. The csv file must have fields named 'patient' and 'sample'.")
```
Comment (robsyme) [inline workflows/sarek.nf:1140]:
```suggestion
                error("Missing field in csv file header. The csv file must have fields named 'patient' and 'sample'.")
```

File: workflows/sarek.nf [hunk 15]
```diff
@@ -1146,12 +1137,10 @@ def extract_csv(csv_file) {
...
             }
             else if (row.patient.contains(" ") || row.sample.contains(" ")) {
-                log.error "Invalid value in csv file. Values for 'patient' and 'sample' can not contain space."
-                System.exit(1)
+                Nextflow.error("Invalid value in csv file. Values for 'patient' and 'sample' can not contain space.")
```
Comment (robsyme) [inline workflows/sarek.nf:1143]:
```suggestion
                error("Invalid value in csv file. Values for 'patient' and 'sample' can not contain space.")
```

File: workflows/sarek.nf [hunk 16]
```diff
@@ -1192,8 +1181,7 @@ def extract_csv(csv_file) {
                 if (params.tools.split(',').contains(tool)) tools_tumor_asked.add(tool)
             }
             if (!tools_tumor_asked.isEmpty()) {
-                log.error('The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : ' + tools_tumor_asked.join(", "))
-                System.exit(1)
+                Nextflow.error('The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : ' + tools_tumor_asked.join(", "))
```
Comment (robsyme) [inline workflows/sarek.nf:1184]:
```suggestion
                error('The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : ' + tools_tumor_asked.join(", "))
```

File: workflows/sarek.nf [hunk 17]
```diff
@@ -1202,8 +1190,7 @@ def extract_csv(csv_file) {
                 if (params.tools.split(',').contains(tool_requiring_normal_samples)) requested_tools_requiring_normal_samples.add(tool_requiring_normal_samples)
             }
             if (!requested_tools_requiring_normal_samples.isEmpty()) {
-                log.error('The sample-sheet only contains tumor-samples, but the following tools, which were requested by the option "tools", expect at least one normal-sample : ' + requested_tools_requiring_normal_samples.join(", "))
-                System.exit(1)
+                Nextflow.error('The sample-sheet only contains tumor-samples, but the following tools, which were requested by the option "tools", expect at least one normal-sample : ' + requested_tools_requiring_normal_samples.join(", "))
```
Comment (robsyme) [inline workflows/sarek.nf:1193]:
```suggestion
                error('The sample-sheet only contains tumor-samples, but the following tools, which were requested by the option "tools", expect at least one normal-sample : ' + requested_tools_requiring_normal_samples.join(", "))
```

File: workflows/sarek.nf [hunk 18]
```diff
@@ -1226,14 +1213,13 @@ def extract_csv(csv_file) {
 
             if (params.step == 'mapping') return [ meta, [ fastq_1, fastq_2 ] ]
             else {
-                log.error "Samplesheet contains fastq files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-                System.exit(1)
+                Nextflow.error("Samplesheet contains fastq files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:1216]:
```suggestion
                error("Samplesheet contains fastq files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 19]
```diff
@@ -1249,8 +1235,7 @@ def extract_csv(csv_file) {
 
             if (params.step != 'annotate') return [ meta, bam, bai ]
             else {
-                log.error "Samplesheet contains bam files but step is `annotate`. The pipeline is expecting vcf files for the annotation. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-                System.exit(1)
+                Nextflow.error("Samplesheet contains bam files but step is `annotate`. The pipeline is expecting vcf files for the annotation. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:1238]:
```suggestion
                error("Samplesheet contains bam files but step is `annotate`. The pipeline is expecting vcf files for the annotation. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 20]
```diff
@@ -1264,8 +1249,7 @@ def extract_csv(csv_file) {
 
             if (!(params.step == 'mapping' || params.step == 'annotate')) return [ meta, cram, crai, table ]
             else {
-                log.error "Samplesheet contains cram files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-                System.exit(1)
+                Nextflow.error("Samplesheet contains cram files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:1252]:
```suggestion
                error("Samplesheet contains cram files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 21]
```diff
@@ -1279,8 +1263,7 @@ def extract_csv(csv_file) {
 
             if (!(params.step == 'mapping' || params.step == 'annotate')) return [ meta, bam, bai, table ]
             else {
-                log.error "Samplesheet contains bam files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-                System.exit(1)
+                Nextflow.error("Samplesheet contains bam files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:1266]:
```suggestion
                error("Samplesheet contains bam files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 22]
```diff
@@ -1293,8 +1276,7 @@ def extract_csv(csv_file) {
 
             if (!(params.step == 'mapping' || params.step == 'annotate')) return [ meta, cram, crai ]
             else {
-                log.error "Samplesheet contains cram files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-                System.exit(1)
+                Nextflow.error("Samplesheet contains cram files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:1279]:
```suggestion
                error("Samplesheet contains cram files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 23]
```diff
@@ -1307,8 +1289,7 @@ def extract_csv(csv_file) {
 
             if (!(params.step == 'mapping' || params.step == 'annotate')) return [ meta, bam, bai ]
             else {
-                log.error "Samplesheet contains bam files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-                System.exit(1)
+                Nextflow.error("Samplesheet contains bam files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:1292]:
```suggestion
                error("Samplesheet contains bam files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 24]
```diff
@@ -1321,12 +1302,10 @@ def extract_csv(csv_file) {
 
             if (params.step == 'annotate') return [ meta, vcf ]
             else {
-                log.error "Samplesheet contains vcf files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations"
-                System.exit(1)
+                Nextflow.error("Samplesheet contains vcf files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```
Comment (robsyme) [inline workflows/sarek.nf:1305]:
```suggestion
                error("Samplesheet contains vcf files but step is `$params.step`. Please check your samplesheet or adjust the step parameter.\nhttps://nf-co.re/sarek/usage#input-samplesheet-configurations")
```

File: workflows/sarek.nf [hunk 25]
```diff
@@ -1321,12 +1302,10 @@ def extract_csv(csv_file) {
...
             }
         } else {
-            log.error "Missing or unknown field in csv file header. Please check your samplesheet"
-            System.exit(1)
+            Nextflow.error("Missing or unknown field in csv file header. Please check your samplesheet")
```
Comment (robsyme) [inline workflows/sarek.nf:1308]:
```suggestion
            error("Missing or unknown field in csv file header. Please check your samplesheet")
```

File: workflows/sarek.nf (hunk 2 above)
Comment (robsyme) [inline workflows/sarek.nf:7]:
```suggestion
```

Comment (robsyme) [reply workflows/sarek.nf]: I've just made a bunch of edits. I tried to batch them up, but I am bad at computers and may have messed it up by including some of them as individual commits. It would be good to squash them before any merge or rebase to dev. Apologies for any extra email/notification noise I may have created in the process :(

**Review by maxulysse — APPROVED** [review]

File: workflows/sarek.nf (hunk 2 above)
Comment (FriederikeHanssen) [reply workflows/sarek.nf]: 🤯 I see, thank you for fixing it up ❤️

**Comment by FriederikeHanssen** [comment]
Hey @robsyme ! I just discussed with @subwaystation on how to apply this to other pipelines, and we noticed that there is yet another `System.exit` call in the `initialise` function. can it be replaced the same way as all the others, since this time the exitcode is 0: https://github.com/nf-core/sarek/blob/9f3ff50fb58cc3a10bd16815e12187f7c490a854/lib/WorkflowMain.groovy#L53

**Comment by subwaystation** [comment]
> Hey @robsyme ! I just discussed with @subwaystation on how to apply this to other pipelines, and we noticed that there is yet another `System.exit` call in the `initialise` function. can it be replaced the same way as all the others, since this time the exitcode is 0:
> 
> https://github.com/nf-core/sarek/blob/9f3ff50fb58cc3a10bd16815e12187f7c490a854/lib/WorkflowMain.groovy#L53

Also note that in https://github.com/nf-core/sarek/blob/9f3ff50fb58cc3a10bd16815e12187f7c490a854/lib/WorkflowMain.groovy#L64 there is only a `log.info` without an actual exit. Just so we don't miss a case.
